/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.lms.view.admin.formpanel;

import edu.ijse.lms.controller.AddExamController;
import edu.ijse.lms.dto.BatchDTO;
import edu.ijse.lms.dto.ExamDTO;
import edu.ijse.lms.dto.SubjectDTO;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import edu.ijse.lms.view.admin.AdminHome;

/**
 *
 * @author Pahansith
 */
public class GrantExamPanel extends javax.swing.JPanel{
    
    
    private AdminHome home;
    private final AddExamController addExamController;
    public GrantExamPanel(AdminHome home) {
        initComponents();
        this.home = home;
        setBounds(0, 0, 800, 630);
        addExamController = new AddExamController(this);
        loadSubjectCombo();
        loadBatchCombo();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        examNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        durationField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        marksField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        questionField = new javax.swing.JTextField();
        subjectCombo = new javax.swing.JComboBox<>();
        examDateField = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        examTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        batchCombo = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 630));
        setLayout(null);

        examNameField.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        add(examNameField);
        examNameField.setBounds(190, 50, 230, 30);

        jLabel2.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Date");
        add(jLabel2);
        jLabel2.setBounds(90, 100, 60, 30);

        jLabel3.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Subject");
        add(jLabel3);
        jLabel3.setBounds(480, 50, 80, 30);

        jLabel5.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Duration");
        add(jLabel5);
        jLabel5.setBounds(70, 150, 80, 30);

        durationField.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        add(durationField);
        durationField.setBounds(190, 150, 230, 30);

        jLabel7.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Total Marks");
        add(jLabel7);
        jLabel7.setBounds(470, 150, 90, 30);

        marksField.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        add(marksField);
        marksField.setBounds(600, 150, 180, 30);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(210, 560, 120, 40);

        addButton.setText("Add Exam");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton);
        addButton.setBounds(40, 560, 150, 40);

        jLabel8.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Exam Name");
        add(jLabel8);
        jLabel8.setBounds(50, 50, 100, 30);

        jLabel9.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Number of Questions");
        add(jLabel9);
        jLabel9.setBounds(10, 200, 160, 30);

        questionField.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        add(questionField);
        questionField.setBounds(190, 200, 230, 30);

        subjectCombo.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        subjectCombo.setBorder(null);
        ((javax.swing.JLabel)subjectCombo.getRenderer()).setHorizontalAlignment(javax.swing.JLabel.CENTER);
        add(subjectCombo);
        subjectCombo.setBounds(600, 50, 180, 30);

        examDateField.setBorder(examNameField.getBorder());
        add(examDateField);
        examDateField.setBounds(190, 100, 230, 30);

        examTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exam Name", "Date", "Batch", "Subject"
            }
        ));
        jScrollPane1.setViewportView(examTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 270, 750, 170);

        jLabel4.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Batch");
        add(jLabel4);
        jLabel4.setBounds(480, 100, 80, 30);

        batchCombo.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        batchCombo.setBorder(null);
        ((javax.swing.JLabel)subjectCombo.getRenderer()).setHorizontalAlignment(javax.swing.JLabel.CENTER);
        add(batchCombo);
        batchCombo.setBounds(600, 100, 180, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        addExamController.addNewQuestion();
        loadTable();
    }//GEN-LAST:event_addButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JComboBox<String> batchCombo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField durationField;
    private org.jdesktop.swingx.JXDatePicker examDateField;
    private javax.swing.JTextField examNameField;
    private javax.swing.JTable examTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField marksField;
    private javax.swing.JTextField questionField;
    private javax.swing.JComboBox<String> subjectCombo;
    // End of variables declaration//GEN-END:variables

    private void loadSubjectCombo() {
        addExamController.loadSubjectCombo();
    }

    public ExamDTO getExamDetail() {
        String name = examNameField.getText();
        Date date = examDateField.getDate();
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        String examDate = format.format(date);
        String duration = durationField.getText();
        int marks = Integer.parseInt(marksField.getText());
        int numberOfQuestion = Integer.parseInt(questionField.getText());
        SubjectDTO subject = (SubjectDTO) subjectCombo.getSelectedItem();
        BatchDTO batch = (BatchDTO) batchCombo.getSelectedItem();
        
        return new ExamDTO(null, name, numberOfQuestion, marks, duration, examDate, batch, subject);
    }

    public void setComboValues(ArrayList<SubjectDTO> subjectList) {
        DefaultComboBoxModel model = (DefaultComboBoxModel) subjectCombo.getModel();
        subjectList.stream().forEach((subjectDTO) -> {
            model.addElement(subjectDTO);
        });
                
    }

    private void loadBatchCombo() {
        addExamController.loadBatchCombo();
    }

    public void setBatchComboValues(ArrayList<BatchDTO> batchList) {
        DefaultComboBoxModel model = (DefaultComboBoxModel)batchCombo.getModel();
        batchList.stream().forEach((batchDTO) -> {
            model.addElement(batchDTO);
        });
    }

    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Message", JOptionPane.INFORMATION_MESSAGE);
    }

    private void loadTable() {
        
        DefaultTableModel model = (DefaultTableModel) examTable.getModel();
        model.setRowCount(0);
        ArrayList<ExamDTO> allExams = addExamController.getAllExams();
        for (ExamDTO exam : allExams) {
            Object[] rowData = {exam.getName(),exam.getDate(),exam.getBatch().getBatchNumber(),exam.getSubject().getName()};
            model.addRow(rowData);
        }
    }
}
