/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.lms.view.admin.formpanel;

import edu.ijse.lms.controller.AddQuestionController;
import edu.ijse.lms.dto.ExamQuestionDTO;
import edu.ijse.lms.dto.SubjectDTO;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import edu.ijse.lms.view.admin.AdminHome;

/**
 *
 * @author Pahansith
 */
public class QuestionAddPanel extends javax.swing.JPanel{
    
    private AdminHome home;
    private final AddQuestionController addQuestionController;
    
    public QuestionAddPanel(AdminHome home) {
        initComponents();
        this.home = home;
        setBounds(0, 0, 800, 630);
        addQuestionController = new AddQuestionController(this);
        loadCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        answer1Field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        answer2Field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        answer3Field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        answer4Field = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        questionArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        answer4Correct = new javax.swing.JRadioButton();
        answer1Correct = new javax.swing.JRadioButton();
        answer2Correct = new javax.swing.JRadioButton();
        answer3Correct = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        answer5Field = new javax.swing.JTextField();
        answer5Correct = new javax.swing.JRadioButton();
        subjectCombo = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 630));
        setLayout(null);

        answer1Field.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        add(answer1Field);
        answer1Field.setBounds(130, 290, 230, 30);

        jLabel1.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Question");
        add(jLabel1);
        jLabel1.setBounds(30, 50, 80, 20);

        jLabel2.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Answer 2");
        add(jLabel2);
        jLabel2.setBounds(20, 330, 80, 30);

        answer2Field.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        add(answer2Field);
        answer2Field.setBounds(130, 330, 230, 30);

        jLabel3.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Subject");
        add(jLabel3);
        jLabel3.setBounds(510, 290, 80, 30);

        jLabel5.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Answer 3");
        add(jLabel5);
        jLabel5.setBounds(20, 370, 80, 30);

        answer3Field.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        add(answer3Field);
        answer3Field.setBounds(130, 370, 230, 30);

        jLabel7.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Answer 4");
        add(jLabel7);
        jLabel7.setBounds(20, 410, 80, 30);

        answer4Field.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        add(answer4Field);
        answer4Field.setBounds(130, 410, 230, 30);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(540, 540, 120, 40);

        addButton.setText("Add Question");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton);
        addButton.setBounds(370, 540, 150, 40);

        questionArea.setColumns(20);
        questionArea.setRows(5);
        jScrollPane2.setViewportView(questionArea);

        add(jScrollPane2);
        jScrollPane2.setBounds(130, 50, 410, 200);

        jLabel8.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Answer 1");
        add(jLabel8);
        jLabel8.setBounds(20, 300, 80, 20);

        answer4Correct.setBackground(new java.awt.Color(255, 255, 255));
        answer4Correct.setText("Correct Answer");
        add(answer4Correct);
        answer4Correct.setBounds(390, 410, 120, 30);

        answer1Correct.setBackground(new java.awt.Color(255, 255, 255));
        answer1Correct.setText("Correct Answer");
        add(answer1Correct);
        answer1Correct.setBounds(390, 290, 120, 30);

        answer2Correct.setBackground(new java.awt.Color(255, 255, 255));
        answer2Correct.setText("Correct Answer");
        add(answer2Correct);
        answer2Correct.setBounds(390, 330, 120, 30);

        answer3Correct.setBackground(new java.awt.Color(255, 255, 255));
        answer3Correct.setText("Correct Answer");
        add(answer3Correct);
        answer3Correct.setBounds(390, 370, 120, 30);

        jLabel9.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Answer 5");
        add(jLabel9);
        jLabel9.setBounds(20, 450, 80, 30);

        answer5Field.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        add(answer5Field);
        answer5Field.setBounds(130, 450, 230, 30);

        answer5Correct.setBackground(new java.awt.Color(255, 255, 255));
        answer5Correct.setText("Correct Answer");
        add(answer5Correct);
        answer5Correct.setBounds(390, 450, 120, 30);

        subjectCombo.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        subjectCombo.setBorder(null);
        ((javax.swing.JLabel)subjectCombo.getRenderer()).setHorizontalAlignment(javax.swing.JLabel.CENTER);
        add(subjectCombo);
        subjectCombo.setBounds(620, 290, 170, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        addQuestionController.addNewQuestion();
    }//GEN-LAST:event_addButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JRadioButton answer1Correct;
    private javax.swing.JTextField answer1Field;
    private javax.swing.JRadioButton answer2Correct;
    private javax.swing.JTextField answer2Field;
    private javax.swing.JRadioButton answer3Correct;
    private javax.swing.JTextField answer3Field;
    private javax.swing.JRadioButton answer4Correct;
    private javax.swing.JTextField answer4Field;
    private javax.swing.JRadioButton answer5Correct;
    private javax.swing.JTextField answer5Field;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea questionArea;
    private javax.swing.JComboBox<String> subjectCombo;
    // End of variables declaration//GEN-END:variables

    public ExamQuestionDTO getQuestion() {
        String text = questionArea.getText();
        String question = text.replace('\n', '$');
        
        String answer1 = answer1Field.getText();
        String answer2 = answer2Field.getText();
        String answer3 = answer3Field.getText();
        String answer4 = answer4Field.getText();
        String answer5 = answer5Field.getText();
        
        String[] answers={answer1,answer2,answer3,answer4,answer5};
        
        boolean is1Correct = answer1Correct.isSelected();
        boolean is2Correct = answer2Correct.isSelected();
        boolean is3Correct = answer3Correct.isSelected();
        boolean is4Correct = answer4Correct.isSelected();
        boolean is5Correct = answer5Correct.isSelected();
        
        boolean[] corrects = {is1Correct,is2Correct,is3Correct,is4Correct,is5Correct};
        
        DefaultComboBoxModel model = (DefaultComboBoxModel) subjectCombo.getModel();
        SubjectDTO subject = (SubjectDTO) model.getSelectedItem();
        
        return  new ExamQuestionDTO(subject, question, answers, corrects,null);
    }

    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Message", JOptionPane.INFORMATION_MESSAGE);
                
    }

    private void loadCombo() {
        addQuestionController.loadComboBox();
    }

    public void setComboValues(ArrayList<SubjectDTO> allSubject) {
        DefaultComboBoxModel model = (DefaultComboBoxModel) subjectCombo.getModel();
        for (SubjectDTO subjectDTO : allSubject) {
            model.addElement(subjectDTO);
        }
        
    }

    

    
}
