/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.lms.view.admin.formpanel;

import edu.ijse.lms.controller.StudentResultsController;
import edu.ijse.lms.dto.BatchDTO;
import edu.ijse.lms.dto.ExamDTO;
import edu.ijse.lms.dto.ExamResultsDTO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import edu.ijse.lms.view.admin.AdminHome;

/**
 *
 * @author Pahansith
 */
public class StudentResultsPanel extends javax.swing.JPanel {

    private final AdminHome home;
    private StudentResultsController controller;
    private ExamDTO examDto;
    private BatchDTO batchDto;
    

    public StudentResultsPanel(AdminHome home) {
        initComponents();
        this.home = home;
        controller = new StudentResultsController(this);
        setBounds(0, 0, 800, 630);
        loadExamResults();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsTable = new javax.swing.JTable();
        activatedExamLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 630));
        setLayout(null);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(220, 500, 120, 40);

        addButton.setText("Print");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton);
        addButton.setBounds(50, 500, 150, 40);

        resultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "NIC", "Marks", "Grade"
            }
        ));
        resultsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(resultsTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 150, 750, 240);

        activatedExamLabel.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        activatedExamLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        activatedExamLabel.setText("No Activated Exams");
        add(activatedExamLabel);
        activatedExamLabel.setBounds(210, 60, 150, 30);

        jLabel9.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Results");
        add(jLabel9);
        jLabel9.setBounds(40, 110, 53, 30);

        jLabel11.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Exam");
        add(jLabel11);
        jLabel11.setBounds(40, 60, 140, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void resultsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultsTableMouseClicked

    }//GEN-LAST:event_resultsTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activatedExamLabel;
    private javax.swing.JButton addButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable resultsTable;
    // End of variables declaration//GEN-END:variables

    

    public void setExam(ExamDTO selectedExam) {
        this.examDto = selectedExam;
        activatedExamLabel.setText(examDto.getName());
    }

    public void setBatch(BatchDTO selectedBatch) {
        this.batchDto = selectedBatch;
    }

    private void loadExamResults() {
        DefaultTableModel model = (DefaultTableModel) resultsTable.getModel();
        ArrayList<ExamResultsDTO> results = controller.getResults();
        String examName = results.get(0).getExam().getName();
        setExamName(examName);
        for (ExamResultsDTO result : results) {
            Object[] rowData = {result.getStudent().getName(),result.getStudent().getNic(),result.getMarks(),result.getGrade()};
            model.addRow(rowData);
        }
        
    }

    private void setExamName(String examName) {
        activatedExamLabel.setText(examName);
    }

    

    

}
