/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.lms.view.admin.formpanel;

import edu.ijse.lms.connector.ServerConnector;
import edu.ijse.lms.controller.StudentRegisterController;
import edu.ijse.lms.dto.StudentRegInfo;
import java.io.Serializable;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import edu.ijse.lms.observer.RegistrationObserver;
import edu.ijse.lms.observer.Subject;
import edu.ijse.lms.service.ServiceFactory;
import edu.ijse.lms.view.admin.AdminHome;

/**
 *
 * @author Pahansith
 */
public class StudentRegisterLoadPanel extends javax.swing.JPanel implements RegistrationObserver{
    
    private AdminHome home;
    private StudentRegisterController studentRegisterController;
    private LinkedList<StudentRegInfo> registerPendingStudentList;
    private int selectedRow;
    /**
     * Creates new form StudentRegisterLoadPanel
     * @param home
     */
    public StudentRegisterLoadPanel(AdminHome home) {
        
        try {
            initComponents();
            
            UnicastRemoteObject.exportObject(this, 0);
            Subject<RegistrationObserver> ob = (Subject<RegistrationObserver>) ServerConnector.getServerConnector().getStudentService();
            ob.registerObserver(this);
            studentRegisterController = new StudentRegisterController(this);
            setBounds(0, 0, 800, 630);
            this.home = home;
            
            setTableValues();
        } catch (NotBoundException ex) {
            Logger.getLogger(StudentRegisterLoadPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(StudentRegisterLoadPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(StudentRegisterLoadPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        nameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nicField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        batchField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dobField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        telephoneField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 630));
        setLayout(null);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        studentTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "NIC", "Batch", "Telephone", "DOB", "Email", "User Name"
            }
        ));
        studentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studentTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 40, 760, 270);

        nameField.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        add(nameField);
        nameField.setBounds(150, 340, 340, 30);

        jLabel1.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Name");
        add(jLabel1);
        jLabel1.setBounds(40, 350, 80, 20);

        jLabel2.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("User Name");
        add(jLabel2);
        jLabel2.setBounds(40, 390, 80, 30);

        userNameField.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        add(userNameField);
        userNameField.setBounds(150, 390, 250, 30);

        jLabel3.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("NIC");
        add(jLabel3);
        jLabel3.setBounds(500, 340, 80, 30);

        nicField.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        add(nicField);
        nicField.setBounds(610, 340, 170, 30);

        jLabel4.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Batch");
        add(jLabel4);
        jLabel4.setBounds(500, 390, 80, 30);

        batchField.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        add(batchField);
        batchField.setBounds(610, 390, 170, 30);

        jLabel5.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Birth Day");
        add(jLabel5);
        jLabel5.setBounds(40, 440, 80, 30);

        dobField.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        add(dobField);
        dobField.setBounds(150, 440, 220, 30);

        jLabel6.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Email");
        add(jLabel6);
        jLabel6.setBounds(500, 440, 80, 30);

        emailField.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        add(emailField);
        emailField.setBounds(610, 440, 170, 30);

        jLabel7.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Telephone");
        add(jLabel7);
        jLabel7.setBounds(40, 490, 80, 30);

        telephoneField.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        add(telephoneField);
        telephoneField.setBounds(150, 490, 230, 30);

        jButton1.setText("Cancel");
        add(jButton1);
        jButton1.setBounds(660, 540, 120, 40);

        jButton2.setText("Confirm Student");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(370, 540, 150, 40);

        jButton3.setText("Ignore");
        add(jButton3);
        jButton3.setBounds(530, 540, 120, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        studentRegisterController.registerNewStudent(registerPendingStudentList.get(selectedRow));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void studentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentTableMouseClicked
        setValuesToField();
    }//GEN-LAST:event_studentTableMouseClicked

    private void setValuesToField() {
        selectedRow = studentTable.getSelectedRow();
        
        if (selectedRow != -1) {
            String name = (String) studentTable.getValueAt(selectedRow, 0);
            String nic = (String) studentTable.getValueAt(selectedRow, 1);
            String batchNumber = Integer.toString((Integer) studentTable.getValueAt(selectedRow, 2));
            String telephone = Integer.toString((Integer) studentTable.getValueAt(selectedRow, 3));
            String dob = (String) studentTable.getValueAt(selectedRow, 4);
            String email = (String) studentTable.getValueAt(selectedRow, 5);
            String userName = (String) studentTable.getValueAt(selectedRow, 6);
            
            
            nameField.setText(name);
            nicField.setText(nic);
            telephoneField.setText(telephone);
            dobField.setText(dob);
            emailField.setText(email);
            userNameField.setText(userName);
            batchField.setText(batchNumber);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField batchField;
    private javax.swing.JTextField dobField;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField nicField;
    private javax.swing.JTable studentTable;
    private javax.swing.JTextField telephoneField;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables

    private void setTableValues() {
        StudentRegisterController.getAllRegisterPendingStudents();
    }

    /*public StudentDTO getStudent() {
    
    }*/

    public void setStudents(LinkedList<StudentRegInfo> allRegisterPendingStudent) {
        this.registerPendingStudentList = allRegisterPendingStudent;
        DefaultTableModel model = (DefaultTableModel) studentTable.getModel();
        model.setRowCount(0);
        for (StudentRegInfo reg : allRegisterPendingStudent) {
            Object rowData[] = {reg.getfName()+" "+reg.getlName(),reg.getNic(),reg.getBatch().getBatchNumber(),reg.getTelephone(),reg.getDob(),reg.getEmail(),reg.getUserName()};
            model.addRow(rowData);
        }
    }

    @Override
    public void update() {
        JOptionPane.showMessageDialog(this, "New Student Registered", "New Registration", JOptionPane.INFORMATION_MESSAGE);
        setTableValues();
    }
}
