/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.lms.view.admin.panel;

import java.awt.Color;
import java.awt.event.MouseEvent;
import edu.ijse.lms.view.admin.AdminHome;
import edu.ijse.lms.view.admin.formpanel.GrantExamPanel;
import edu.ijse.lms.view.admin.formpanel.ProceedExamPanel;
import edu.ijse.lms.view.admin.formpanel.QuestionAddPanel;
import edu.ijse.lms.view.admin.formpanel.TriggerExamPanel;
import edu.ijse.lms.view.student.StudentHome;
import edu.ijse.lms.view.student.formpanel.FaceExamPanel;

/**
 *
 * @author Pahansith
 */
public class ExamOptionsPanel extends javax.swing.JPanel {
    
    private AdminHome home;
    /**
     * Creates new form StudentOptionsPanel
     * @param home
     */
    public ExamOptionsPanel(AdminHome home) {
        initComponents();
        this.home = home;
        setBounds(0, 0, 800, 70);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addExamLabel = new javax.swing.JLabel();
        addQuestionLabel = new javax.swing.JLabel();
        triggerExamLabel = new javax.swing.JLabel();
        proceedExamLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 70));

        addExamLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addExamLabel.setForeground(new java.awt.Color(165, 170, 174));
        addExamLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addExamLabel.setText("Add Exam");
        addExamLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addExamLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addExamLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addExamLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addExamLabelMouseExited(evt);
            }
        });

        addQuestionLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addQuestionLabel.setForeground(new java.awt.Color(165, 170, 174));
        addQuestionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addQuestionLabel.setText("Add Questions");
        addQuestionLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addQuestionLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addQuestionLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addQuestionLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addQuestionLabelMouseExited(evt);
            }
        });

        triggerExamLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        triggerExamLabel.setForeground(new java.awt.Color(165, 170, 174));
        triggerExamLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        triggerExamLabel.setText("Trigger Exam");
        triggerExamLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        triggerExamLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                triggerExamLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                triggerExamLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                triggerExamLabelMouseExited(evt);
            }
        });

        proceedExamLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        proceedExamLabel1.setForeground(new java.awt.Color(165, 170, 174));
        proceedExamLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proceedExamLabel1.setText("Activate Exam");
        proceedExamLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        proceedExamLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proceedExamLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                proceedExamLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                proceedExamLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addExamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addQuestionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proceedExamLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(triggerExamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(triggerExamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(proceedExamLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addExamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addQuestionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addExamLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addExamLabelMouseEntered
        changeColor(evt);
    }//GEN-LAST:event_addExamLabelMouseEntered

    private void addExamLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addExamLabelMouseExited
        setBackColor(evt);
    }//GEN-LAST:event_addExamLabelMouseExited

    private void addQuestionLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addQuestionLabelMouseEntered
        changeColor(evt);
    }//GEN-LAST:event_addQuestionLabelMouseEntered

    private void addQuestionLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addQuestionLabelMouseExited
        setBackColor(evt);
    }//GEN-LAST:event_addQuestionLabelMouseExited

    private void triggerExamLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_triggerExamLabelMouseEntered
        changeColor(evt);
    }//GEN-LAST:event_triggerExamLabelMouseEntered

    private void triggerExamLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_triggerExamLabelMouseExited
        setBackColor(evt);
    }//GEN-LAST:event_triggerExamLabelMouseExited

    private void addQuestionLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addQuestionLabelMouseClicked
        home.loadPanel.removeAll();
        home.loadPanel.add(new QuestionAddPanel(home));
        home.loadPanel.repaint();
        home.loadPanel.revalidate();
    }//GEN-LAST:event_addQuestionLabelMouseClicked

    private void triggerExamLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_triggerExamLabelMouseClicked
        home.loadPanel.removeAll();
        home.loadPanel.add(new TriggerExamPanel(home));
        home.loadPanel.repaint();
        home.loadPanel.revalidate();
    }//GEN-LAST:event_triggerExamLabelMouseClicked

    private void addExamLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addExamLabelMouseClicked
        home.loadPanel.removeAll();
        home.loadPanel.add(new GrantExamPanel(home));
        home.loadPanel.repaint();
        home.loadPanel.revalidate();
    }//GEN-LAST:event_addExamLabelMouseClicked

    private void proceedExamLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedExamLabel1MouseEntered
        changeColor(evt);
    }//GEN-LAST:event_proceedExamLabel1MouseEntered

    private void proceedExamLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedExamLabel1MouseExited
        setBackColor(evt);
    }//GEN-LAST:event_proceedExamLabel1MouseExited

    private void proceedExamLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedExamLabel1MouseClicked
        home.loadPanel.removeAll();
        home.loadPanel.add(new ProceedExamPanel(home));
        home.loadPanel.repaint();
        home.loadPanel.revalidate();
    }//GEN-LAST:event_proceedExamLabel1MouseClicked

    
    private void changeColor(MouseEvent evt) {
        javax.swing.JLabel selectedLabel = (javax.swing.JLabel)evt.getSource();
        selectedLabel.setForeground(new Color(2, 150, 220));
        
    }

    private void setBackColor(MouseEvent evt) {
        javax.swing.JLabel selectedLabel = (javax.swing.JLabel)evt.getSource();
        selectedLabel.setForeground(new Color(165,170,174));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addExamLabel;
    private javax.swing.JLabel addQuestionLabel;
    private javax.swing.JLabel proceedExamLabel1;
    private javax.swing.JLabel triggerExamLabel;
    // End of variables declaration//GEN-END:variables
}
