/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.lms.view.admin.panel;

import edu.ijse.lms.view.admin.AdminHome;

/**
 *
 * @author Pahansith
 */
public class StudentOptionsPanel extends javax.swing.JPanel {
    
    private AdminHome home;
    /**
     * Creates new form StudentOptionsPanel
     * @param home
     */
    public StudentOptionsPanel(AdminHome home) {
        initComponents();
        this.home = home;
        setBounds(0, 0, 800, 70);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentLabel2 = new javax.swing.JLabel();
        studentLabel3 = new javax.swing.JLabel();
        studentLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 70));

        studentLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        studentLabel2.setForeground(new java.awt.Color(165, 170, 174));
        studentLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentLabel2.setText("Register");
        studentLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentLabel2MouseExited(evt);
            }
        });

        studentLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        studentLabel3.setForeground(new java.awt.Color(165, 170, 174));
        studentLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentLabel3.setText("Profile");
        studentLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentLabel3MouseExited(evt);
            }
        });

        studentLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        studentLabel1.setForeground(new java.awt.Color(165, 170, 174));
        studentLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentLabel1.setText("FeedBack");
        studentLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(studentLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(studentLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(studentLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 470, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void studentLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLabel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_studentLabel2MouseEntered

    private void studentLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLabel2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_studentLabel2MouseExited

    private void studentLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLabel3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_studentLabel3MouseEntered

    private void studentLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLabel3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_studentLabel3MouseExited

    private void studentLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLabel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_studentLabel1MouseEntered

    private void studentLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLabel1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_studentLabel1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel studentLabel1;
    private javax.swing.JLabel studentLabel2;
    private javax.swing.JLabel studentLabel3;
    // End of variables declaration//GEN-END:variables
}
