/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.lms.view.student.formpanel;

import edu.ijse.lms.controller.ViewMarksController;
import edu.ijse.lms.dto.ExamDTO;
import edu.ijse.lms.dto.ExamResultsDTO;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import edu.ijse.lms.view.student.StudentHome;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Pahansith
 */
public class ViewMarksPanel extends javax.swing.JPanel {

    private StudentHome home;
    
    private final ViewMarksController viewMarksController;

    public ViewMarksPanel(StudentHome home) {
        initComponents();
        this.home = home;
        setBounds(0, 0, 800, 630);
        viewMarksController = new ViewMarksController(this);
        loadStudentMarks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        questionNumberLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        numOfQuestionField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        durationField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        subjectField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        totalMarksField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        subjectField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        examTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 630));
        setPreferredSize(new java.awt.Dimension(800, 630));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        questionNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        add(questionNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 60, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.setLayout(null);

        numOfQuestionField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numOfQuestionField.setPreferredSize(new java.awt.Dimension(6, 30));
        numOfQuestionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numOfQuestionFieldActionPerformed(evt);
            }
        });
        jPanel1.add(numOfQuestionField);
        numOfQuestionField.setBounds(260, 80, 370, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Number of Questions : ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 80, 160, 30);

        durationField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        durationField.setPreferredSize(new java.awt.Dimension(6, 30));
        jPanel1.add(durationField);
        durationField.setBounds(260, 30, 370, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Exam : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 30, 150, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Total Marks : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 130, 160, 30);

        subjectField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subjectField.setPreferredSize(new java.awt.Dimension(6, 30));
        jPanel1.add(subjectField);
        subjectField.setBounds(260, 180, 370, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Your Marks : ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 180, 100, 30);

        totalMarksField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalMarksField.setPreferredSize(new java.awt.Dimension(6, 30));
        jPanel1.add(totalMarksField);
        totalMarksField.setBounds(260, 130, 370, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Exam Detail");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 0, 150, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Grade : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 230, 100, 30);

        subjectField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subjectField1.setPreferredSize(new java.awt.Dimension(6, 30));
        jPanel1.add(subjectField1);
        subjectField1.setBounds(260, 230, 370, 30);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 740, 280));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel2.setLayout(null);

        examTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exam Name", "Date", "Marks", "Grade"
            }
        ));
        jScrollPane1.setViewportView(examTable);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 720, 180);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Results Released Exams");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(30, 0, 210, 40);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 740, 270));
    }// </editor-fold>//GEN-END:initComponents

    private void numOfQuestionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numOfQuestionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numOfQuestionFieldActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField durationField;
    private javax.swing.JTable examTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numOfQuestionField;
    private javax.swing.JLabel questionNumberLabel;
    private javax.swing.JTextField subjectField;
    private javax.swing.JTextField subjectField1;
    private javax.swing.JTextField totalMarksField;
    // End of variables declaration//GEN-END:variables

    

    

    @Override
    public boolean equals(Object o) {
        if (o instanceof ViewMarksPanel) {
            return this.home.getStudent().getNic().equals(((ViewMarksPanel) o).home.getStudent().getNic());
        }
        return false;
    }

    private void loadStudentMarks() {
        ArrayList<ExamResultsDTO> marks = viewMarksController.getMarks(home.getStudent());
        DefaultTableModel model = (DefaultTableModel) examTable.getModel();
        for (ExamResultsDTO mark : marks) {
            Object[] rowData = {mark.getExam().getName(),mark.getExam().getDate(),mark.getMarks(),mark.getGrade()};
            model.addRow(rowData);
        }
    }

    

}
