/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.lms.view.admin;

import edu.ijse.lms.dto.AdministrativeDTO;
import java.awt.Color;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;
import edu.ijse.lms.view.admin.formpanel.GrantExamPanel;
import edu.ijse.lms.view.admin.formpanel.QuestionAddPanel;
import edu.ijse.lms.view.admin.formpanel.StudentRegisterLoadPanel;
import edu.ijse.lms.view.admin.panel.ExamOptionsPanel;
import edu.ijse.lms.view.student.panel.StudentExamOptionsPanel;
import edu.ijse.lms.view.admin.panel.StudentOptionsPanel;
import edu.ijse.lms.view.custom.GUISuper;

/**
 *
 * @author Pahansith
 */
public class AdminHome extends javax.swing.JFrame implements GUISuper {

    /**
     * Creates new form AdminHome
     */
    
    private AdministrativeDTO admin;
    public AdminHome(AdministrativeDTO admin) {
        initComponents();
        this.admin = admin;
        setAdmin();
        
    }
    
    public AdminHome(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        studentLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        adminNameLabel = new javax.swing.JLabel();
        loadPanel = new javax.swing.JPanel();
        graphPanel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        graphPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        graphPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        optionsPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(990, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonPanel.setBackground(new java.awt.Color(49, 56, 62));
        ButtonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(165, 170, 174));
        jLabel2.setForeground(new java.awt.Color(165, 170, 174));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, 60));

        studentLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        studentLabel.setForeground(new java.awt.Color(165, 170, 174));
        studentLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studentLabel.setText("Student");
        studentLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentLabelMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentLabelMouseClicked(evt);
            }
        });
        ButtonPanel.add(studentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 100, 60));

        jLabel3.setBackground(new java.awt.Color(165, 170, 174));
        jLabel3.setForeground(new java.awt.Color(165, 170, 174));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 60, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(165, 170, 174));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Exam");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        ButtonPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 100, 60));

        jLabel5.setBackground(new java.awt.Color(165, 170, 174));
        jLabel5.setForeground(new java.awt.Color(165, 170, 174));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 60, 60));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(165, 170, 174));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Courses");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        ButtonPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 100, 60));

        jLabel8.setBackground(new java.awt.Color(165, 170, 174));
        jLabel8.setForeground(new java.awt.Color(165, 170, 174));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 60, 60));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(165, 170, 174));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Settings");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        ButtonPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 100, 60));

        jLabel12.setBackground(new java.awt.Color(165, 170, 174));
        jLabel12.setForeground(new java.awt.Color(165, 170, 174));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 60, 60));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(165, 170, 174));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Admin");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        ButtonPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 100, 60));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(165, 170, 174));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Subjects");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        ButtonPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 100, 60));

        jLabel11.setBackground(new java.awt.Color(165, 170, 174));
        jLabel11.setForeground(new java.awt.Color(165, 170, 174));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 50, 60));

        jLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel.setForeground(new java.awt.Color(0, 255, 255));
        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel.setText("Logged in As");
        ButtonPanel.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 150, 30));

        adminNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        adminNameLabel.setForeground(new java.awt.Color(0, 255, 255));
        adminNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonPanel.add(adminNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 150, 30));

        jPanel1.add(ButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 190, 630));

        loadPanel.setBackground(new java.awt.Color(255, 255, 255));
        loadPanel.setMinimumSize(new java.awt.Dimension(800, 630));
        loadPanel.setPreferredSize(new java.awt.Dimension(800, 630));
        loadPanel.setLayout(null);

        graphPanel5.setBackground(new java.awt.Color(65, 131, 215));
        graphPanel5.setMinimumSize(new java.awt.Dimension(276, 128));
        graphPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Anadi", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(157, 205, 234));
        jLabel22.setText("Register Student");
        graphPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 11, 130, 29));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setOpaque(true);
        graphPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, 3));

        jLabel25.setFont(new java.awt.Font("Open Sans Semibold", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(144, 198, 237));
        jLabel25.setText("approve student requests");
        graphPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 190, -1));

        loadPanel.add(graphPanel5);
        graphPanel5.setBounds(290, 30, 230, 128);

        graphPanel4.setBackground(new java.awt.Color(255, 184, 73));
        graphPanel4.setMinimumSize(new java.awt.Dimension(276, 128));
        graphPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setOpaque(true);
        graphPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, 3));

        jLabel21.setFont(new java.awt.Font("Open Sans Semibold", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(239, 253, 140));
        jLabel21.setText("improve question bank");
        graphPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 190, -1));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Anadi", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(239, 253, 140));
        jLabel26.setText("Add Questions");
        graphPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 11, 150, 29));

        loadPanel.add(graphPanel4);
        graphPanel4.setBounds(530, 30, 230, 128);

        graphPanel3.setBackground(new java.awt.Color(142, 68, 173));
        graphPanel3.setMinimumSize(new java.awt.Dimension(276, 128));
        graphPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Anadi", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(203, 180, 213));
        jLabel16.setText("New Exam");
        graphPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 11, 86, 29));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setOpaque(true);
        graphPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, 3));

        jLabel18.setFont(new java.awt.Font("Open Sans Semibold", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(203, 180, 213));
        jLabel18.setText("grant a new exam for students");
        graphPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 190, -1));

        loadPanel.add(graphPanel3);
        graphPanel3.setBounds(40, 30, 230, 128);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/admin/image/Home.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        loadPanel.add(jPanel3);
        jPanel3.setBounds(20, 220, 760, 390);

        jPanel1.add(loadPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 800, 630));

        optionsPanel.setBackground(new java.awt.Color(255, 255, 255));
        optionsPanel.setLayout(null);
        jPanel1.add(optionsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 800, 70));

        jPanel2.setBackground(new java.awt.Color(34, 39, 42));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/admin/image/LabelModel.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void studentLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLabelMouseEntered
        changeColor(evt);
    }//GEN-LAST:event_studentLabelMouseEntered

    private void studentLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLabelMouseExited
        setBackColor(evt);
    }//GEN-LAST:event_studentLabelMouseExited

    private void studentLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLabelMouseClicked
        optionsPanel.removeAll();
        optionsPanel.add(new StudentOptionsPanel(this));
        optionsPanel.repaint();
        optionsPanel.revalidate();
        
        loadPanel.removeAll();
        StudentRegisterLoadPanel studentRegisterLoadPanel = new StudentRegisterLoadPanel(this);
        loadPanel.add(studentRegisterLoadPanel);
        loadPanel.repaint();
        loadPanel.revalidate();
        
    }//GEN-LAST:event_studentLabelMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        optionsPanel.removeAll();
        optionsPanel.add(new ExamOptionsPanel(this));
        optionsPanel.repaint();
        optionsPanel.revalidate();
        
        loadPanel.removeAll();
        GrantExamPanel addPanel = new GrantExamPanel(this);
        loadPanel.add(addPanel);
        loadPanel.repaint();
        loadPanel.revalidate();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        changeColor(evt);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        setBackColor(evt);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        changeColor(evt);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        setBackColor(evt);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        changeColor(evt);
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        setBackColor(evt);
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        changeColor(evt);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        setBackColor(evt);
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        changeColor(evt);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        setBackColor(evt);
    }//GEN-LAST:event_jLabel7MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JLabel adminNameLabel;
    private javax.swing.JPanel graphPanel3;
    private javax.swing.JPanel graphPanel4;
    private javax.swing.JPanel graphPanel5;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel loadPanel;
    private javax.swing.JPanel optionsPanel;
    private javax.swing.JLabel studentLabel;
    // End of variables declaration//GEN-END:variables

    private void changeColor(MouseEvent evt) {
        javax.swing.JLabel selectedLabel = (javax.swing.JLabel)evt.getSource();
        selectedLabel.setForeground(new Color(2, 150, 220));
        
    }

    private void setBackColor(MouseEvent evt) {
        javax.swing.JLabel selectedLabel = (javax.swing.JLabel)evt.getSource();
        selectedLabel.setForeground(new Color(165,170,174));
    }

    private void setAdmin() {
        adminNameLabel.setText(admin.getName());
    }
    
    public AdministrativeDTO getAdmin(){
        return this.admin;
    }
    
    public JPanel getLoadPanel(){
        return loadPanel;
    }
}
