/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.lms.view.common;

import edu.ijse.lms.controller.AccountCreateController;
import edu.ijse.lms.dto.BatchDTO;
import edu.ijse.lms.dto.StudentRegInfo;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Pahansith
 */
public class CreateAccountForm extends javax.swing.JFrame{

    private DefaultComboBoxModel model;

    
    
    /**
     * Creates new form CreateAccountForm
     */
    public CreateAccountForm() {
        initComponents();
        loadCombo();
    }

    private void loadCombo() {
        ArrayList<BatchDTO> batchesAvailable = AccountCreateController.getBatchDetails();
        if (batchesAvailable != null) {
            model = (DefaultComboBoxModel) batchCombo.getModel();
            for (BatchDTO batchDTO : batchesAvailable) {
                model.addElement(batchDTO);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fNameField = new javax.swing.JTextField();
        lNameField = new javax.swing.JTextField();
        yearField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        telephoneField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        signUpButton = new javax.swing.JButton();
        confPasswordField = new javax.swing.JPasswordField();
        passwordField = new javax.swing.JPasswordField();
        userNameField = new javax.swing.JTextField();
        dateField = new javax.swing.JTextField();
        monthField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        batchCombo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        nicField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 647, -1));

        jLabel1.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("First Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 113, 129, 29));

        jLabel2.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Last Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 154, 129, 29));

        jLabel3.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("User Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 194, 129, -1));

        jLabel4.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Batch");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 129, 31));

        jLabel6.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 129, 31));

        jLabel7.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Telephone");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 129, 31));

        jLabel8.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Password");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 129, 31));

        jLabel9.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Confirm Password");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, 31));

        fNameField.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jPanel1.add(fNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 390, 25));

        lNameField.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jPanel1.add(lNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 389, 25));

        yearField.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jPanel1.add(yearField, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 110, 30));

        emailField.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jPanel1.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 300, 25));

        telephoneField.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jPanel1.add(telephoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 160, 25));

        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelButton.setText("Cancel");
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 140, 30));

        signUpButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signUpButton.setText("SignUp");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        jPanel1.add(signUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 140, 30));
        jPanel1.add(confPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 390, 25));
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 390, 25));

        userNameField.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jPanel1.add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 260, 25));

        dateField.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jPanel1.add(dateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 100, 30));

        monthField.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jPanel1.add(monthField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 120, 30));

        jLabel10.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Date of Birth");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 129, 31));

        batchCombo.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        batchCombo.setBorder(null);
        ((javax.swing.JLabel)batchCombo.getRenderer()).setHorizontalAlignment(javax.swing.JLabel.CENTER);
        jPanel1.add(batchCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 100, 30));

        jLabel11.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("NIC");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 129, 30));

        try {
            nicField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########V")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        nicField.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jPanel1.add(nicField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 160, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        AccountCreateController.signUp();
    }//GEN-LAST:event_signUpButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> batchCombo;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPasswordField confPasswordField;
    private javax.swing.JTextField dateField;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField fNameField;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lNameField;
    private javax.swing.JTextField monthField;
    private javax.swing.JFormattedTextField nicField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton signUpButton;
    private javax.swing.JTextField telephoneField;
    private javax.swing.JTextField userNameField;
    private javax.swing.JTextField yearField;
    // End of variables declaration//GEN-END:variables

    public StudentRegInfo collectData() {
        String fName = fNameField.getText();
        String lName = lNameField.getText();
        String userName = userNameField.getText();
        String dob = dateField.getText()+"/"+monthField.getText()+"/"+yearField.getText();
        
        String nic = nicField.getText();
        String email = emailField.getText();
        int telephone =Integer.parseInt(telephoneField.getText());
        char[] arr1 = passwordField.getPassword();
        String password = new String(arr1);
        char[] arr2 = confPasswordField.getPassword();
        String confPassword = new String(arr2);
        BatchDTO batch = (BatchDTO) model.getSelectedItem();
        return  new StudentRegInfo(fName, lName, userName, nic, dob, telephone, batch, password, email, confPassword);
    }

    public void showError(String err) {
        JOptionPane.showMessageDialog(this, err, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void showMessage(String message){
        JOptionPane.showMessageDialog(this, message, "Message", JOptionPane.INFORMATION_MESSAGE);
    }

}
